version: '3.8'

services:
  app:
    image: your-app-image:latest
    container_name: spring_app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: railway
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "20210:3306"
    env_file:
      - .env

  redis:
    image: redis:alpine
    container_name: redis_cache
    restart: always
    command: sh -c "redis-server --requirepass $${REDIS_PASSWORD}"
    ports:
      - "52777:6379"
    env_file:
      - .env
