openapi: 3.0.3
info:
  title: Message Service API
  version: 1.0.0
  description: API để đăng nhập người dùng
paths:
  /login:
    post:
      summary: Đăng nhập người dùng
      description: Đăng nhập và nhận JWT token nếu thành công
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Phản hồi đăng nhập thành công hoặc lỗi nghiệp vụ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseString'
        '500':
          description: Lỗi hệ thống
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseString'
components:
  schemas:
    LoginRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          example: "user123"
          description: Tên đăng nhập của người dùng
        password:
          type: string
          example: "password123"
          description: Mật khẩu của người dùng
    ApiResponseString:
      type: object
      properties:
        code:
          type: string
          description: Mã trạng thái, ví dụ "00" là thành công
          example: "00"
        success:
          type: boolean
          description: Trạng thái thành công hay thất bại
          example: true
        message:
          type: string
          description: Thông điệp trả về từ server
          example: "Đăng nhập thành công"
        displayMessage:
          type: string
          description: Thông điệp hiển thị cho người dùng
          example: "Đăng nhập thành công"
        responseTime:
          type: string
          format: date-time
          description: Thời gian phản hồi theo định dạng ISO 8601
          example: "2025-05-27T13:00:00+07:00"
        data:
          type: string
          nullable: true
          description: Dữ liệu trả về (token JWT)
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."

